# Generated by Django 3.1.7 on 2021-03-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210301_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortdescription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
