# Generated by Django 3.1.7 on 2021-03-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_shortdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shortdescription',
            field=models.TextField(blank=True, max_length=10, verbose_name='Краткое описание'),
        ),
    ]
